create extension if not exists pgcrypto;
create extension if not exists citext;

create schema if not exists private;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.perfis (
  id smallint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  descricao text,
  created_at timestamptz not null default now(),
  constraint perfis_codigo_check
    check (
      codigo in (
        'aluno',
        'professor',
        'secretaria',
        'coordenador',
        'coordenador_master'
      )
    )
);

create table if not exists public.unidades (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  sigla varchar(20) not null,
  slug text not null,
  cidade text,
  estado char(2),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint unidades_slug_uk unique (slug),
  constraint unidades_sigla_uk unique (sigla),
  constraint unidades_estado_check
    check (estado is null or estado ~ '^[A-Z]{2}$')
);

insert into public.unidades (nome, sigla, slug, cidade, estado, ativo)
values ('Unidade Padrão', 'PAD', 'unidade-padrao', null, null, true)
on conflict (slug) do update
set
  nome = excluded.nome,
  sigla = excluded.sigla,
  ativo = excluded.ativo;

create or replace function public.default_unidade_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.unidades
  where slug = 'unidade-padrao'
  limit 1;
$$;

create table if not exists public.usuarios (
  id uuid primary key references auth.users (id) on delete cascade,
  perfil_id smallint not null references public.perfis (id),
  unidade_id uuid references public.unidades (id) on delete restrict,
  email citext not null unique,
  nome_completo text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_usuarios_perfil_id on public.usuarios (perfil_id);
create index if not exists idx_usuarios_ativo on public.usuarios (ativo);
create index if not exists idx_usuarios_unidade_id on public.usuarios (unidade_id);

create table if not exists public.alunos (
  usuario_id uuid primary key references public.usuarios (id) on delete cascade,
  unidade_id uuid references public.unidades (id) on delete restrict,
  matricula varchar(30) not null unique,
  curso text not null default 'Fisioterapia',
  nome_social text,
  data_ingresso date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.professores (
  usuario_id uuid primary key references public.usuarios (id) on delete cascade,
  unidade_id uuid references public.unidades (id) on delete restrict,
  registro_funcional varchar(30) unique,
  departamento text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coordenadores (
  usuario_id uuid primary key references public.usuarios (id) on delete cascade,
  unidade_id uuid references public.unidades (id) on delete restrict,
  cargo text not null default 'Coordenador de Estágio',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coordenadores_master (
  usuario_id uuid primary key references public.usuarios (id) on delete cascade,
  cargo text not null default 'Coordenador Master',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.semestres (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  codigo varchar(10) not null unique,
  nome text not null,
  data_inicio date not null,
  data_fim date not null,
  status text not null default 'planejado',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint semestres_periodo_check check (data_inicio < data_fim),
  constraint semestres_status_check check (status in ('planejado', 'ativo', 'encerrado'))
);

alter table public.usuarios
  add column if not exists unidade_id uuid references public.unidades (id) on delete restrict;

alter table public.alunos
  add column if not exists unidade_id uuid references public.unidades (id) on delete restrict;

alter table public.professores
  add column if not exists unidade_id uuid references public.unidades (id) on delete restrict;

alter table public.coordenadores
  add column if not exists unidade_id uuid references public.unidades (id) on delete restrict;

alter table public.semestres
  add column if not exists unidade_id uuid references public.unidades (id) on delete restrict;

alter table public.usuarios
  alter column unidade_id set default public.default_unidade_id();

alter table public.alunos
  alter column unidade_id set default public.default_unidade_id();

alter table public.professores
  alter column unidade_id set default public.default_unidade_id();

alter table public.coordenadores
  alter column unidade_id set default public.default_unidade_id();

alter table public.semestres
  alter column unidade_id set default public.default_unidade_id();

update public.usuarios
set unidade_id = public.default_unidade_id()
where unidade_id is null;

update public.alunos
set unidade_id = public.default_unidade_id()
where unidade_id is null;

update public.professores
set unidade_id = public.default_unidade_id()
where unidade_id is null;

update public.coordenadores
set unidade_id = public.default_unidade_id()
where unidade_id is null;

update public.semestres
set unidade_id = public.default_unidade_id()
where unidade_id is null;

create index if not exists idx_alunos_unidade_id on public.alunos (unidade_id);
create index if not exists idx_professores_unidade_id on public.professores (unidade_id);
create index if not exists idx_coordenadores_unidade_id on public.coordenadores (unidade_id);
create index if not exists idx_semestres_unidade_id on public.semestres (unidade_id);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'alunos_matricula_key'
      and conrelid = 'public.alunos'::regclass
  ) then
    alter table public.alunos
      drop constraint alunos_matricula_key;
  end if;
end;
$$;

create unique index if not exists idx_alunos_unidade_matricula_uk
  on public.alunos (unidade_id, matricula);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'professores_registro_funcional_key'
      and conrelid = 'public.professores'::regclass
  ) then
    alter table public.professores
      drop constraint professores_registro_funcional_key;
  end if;
end;
$$;

create unique index if not exists idx_professores_unidade_registro_uk
  on public.professores (unidade_id, registro_funcional)
  where registro_funcional is not null;

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'semestres_codigo_key'
      and conrelid = 'public.semestres'::regclass
  ) then
    alter table public.semestres
      drop constraint semestres_codigo_key;
  end if;
end;
$$;

create unique index if not exists idx_semestres_unidade_codigo_uk
  on public.semestres (unidade_id, codigo);

create table if not exists public.blocos_estagio (
  id smallint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  ordem smallint not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blocos_estagio_codigo_check
    check (codigo in ('bloco_1', 'bloco_2'))
);

create table if not exists public.areas_estagio (
  id uuid primary key default gen_random_uuid(),
  bloco_id smallint not null references public.blocos_estagio (id) on delete restrict,
  codigo text not null unique,
  nome text not null unique,
  ordem smallint not null,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint areas_estagio_ordem_uk unique (bloco_id, ordem)
);

create index if not exists idx_areas_estagio_bloco_id
  on public.areas_estagio (bloco_id, ativa, ordem);

create table if not exists public.turmas (
  id uuid primary key default gen_random_uuid(),
  semestre_id uuid not null references public.semestres (id) on delete restrict,
  codigo varchar(30) not null,
  nome text not null,
  area_estagio text not null,
  coordenador_id uuid references public.coordenadores (usuario_id) on delete restrict,
  capacidade smallint check (capacidade is null or capacidade > 0),
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint turmas_codigo_semestre_uk unique (semestre_id, codigo)
);

create index if not exists idx_turmas_semestre_id on public.turmas (semestre_id);
create index if not exists idx_turmas_coordenador_id on public.turmas (coordenador_id);

alter table public.turmas
  add column if not exists area_estagio_id uuid references public.areas_estagio (id) on delete restrict;

create index if not exists idx_turmas_area_estagio_id
  on public.turmas (area_estagio_id);

create table if not exists public.matriculas_turma (
  id uuid primary key default gen_random_uuid(),
  turma_id uuid not null references public.turmas (id) on delete restrict,
  aluno_id uuid not null references public.alunos (usuario_id) on delete restrict,
  numero_chamada smallint,
  status text not null default 'ativa',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matriculas_turma_status_check
    check (status in ('ativa', 'trancada', 'cancelada', 'concluida')),
  constraint matriculas_turma_uk unique (turma_id, aluno_id)
);

create index if not exists idx_matriculas_turma_aluno_id on public.matriculas_turma (aluno_id);
create index if not exists idx_matriculas_turma_turma_id on public.matriculas_turma (turma_id);

alter table public.alunos
  add column if not exists celular varchar(30);

create table if not exists public.professor_areas_estagio (
  id uuid primary key default gen_random_uuid(),
  professor_id uuid not null references public.professores (usuario_id) on delete cascade,
  area_estagio_id uuid not null references public.areas_estagio (id) on delete cascade,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint professor_areas_estagio_uk unique (professor_id, area_estagio_id)
);

create index if not exists idx_professor_areas_estagio_professor_id
  on public.professor_areas_estagio (professor_id, ativo);
create index if not exists idx_professor_areas_estagio_area_id
  on public.professor_areas_estagio (area_estagio_id, ativo);

create table if not exists public.vinculos_professor_aluno (
  id uuid primary key default gen_random_uuid(),
  professor_id uuid not null references public.professores (usuario_id) on delete restrict,
  matricula_turma_id uuid not null references public.matriculas_turma (id) on delete restrict,
  responsavel_principal boolean not null default false,
  ativo boolean not null default true,
  data_inicio date not null default current_date,
  data_fim date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vinculos_professor_aluno_periodo_check
    check (data_fim is null or data_fim >= data_inicio),
  constraint vinculos_professor_aluno_uk unique (professor_id, matricula_turma_id)
);

create index if not exists idx_vinculos_professor_aluno_professor_id
  on public.vinculos_professor_aluno (professor_id, ativo);
create index if not exists idx_vinculos_professor_aluno_matricula_turma_id
  on public.vinculos_professor_aluno (matricula_turma_id, ativo);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'vinculos_professor_aluno_uk'
      and conrelid = 'public.vinculos_professor_aluno'::regclass
  ) then
    alter table public.vinculos_professor_aluno
      drop constraint vinculos_professor_aluno_uk;
  end if;
end;
$$;

create unique index if not exists idx_vinculos_professor_aluno_unico_ativo
  on public.vinculos_professor_aluno (professor_id, matricula_turma_id)
  where ativo = true;

create table if not exists public.grupos_avaliacao (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nome text not null,
  ordem smallint not null unique,
  peso_percentual numeric(5,2) not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint grupos_avaliacao_peso_check
    check (peso_percentual > 0 and peso_percentual <= 100)
);

create table if not exists public.criterios_avaliacao (
  id uuid primary key default gen_random_uuid(),
  grupo_id uuid not null references public.grupos_avaliacao (id) on delete restrict,
  codigo text not null unique,
  nome text not null,
  descricao text,
  ordem smallint not null,
  peso_percentual numeric(5,2) not null,
  escala_maxima numeric(4,2) not null default 10.00,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint criterios_avaliacao_peso_check
    check (peso_percentual > 0 and peso_percentual <= 100),
  constraint criterios_avaliacao_escala_check
    check (escala_maxima > 0),
  constraint criterios_avaliacao_ordem_uk unique (grupo_id, ordem)
);

create index if not exists idx_criterios_avaliacao_grupo_id on public.criterios_avaliacao (grupo_id);

create table if not exists public.avaliacoes (
  id uuid primary key default gen_random_uuid(),
  matricula_turma_id uuid not null references public.matriculas_turma (id) on delete restrict,
  professor_id uuid not null references public.professores (usuario_id) on delete restrict,
  semestre_id uuid not null references public.semestres (id) on delete restrict,
  tipo_lancamento text not null default 'parcial',
  referencia text not null,
  observacoes text,
  avaliacao_origem_id uuid references public.avaliacoes (id) on delete restrict,
  avaliacao_raiz_id uuid references public.avaliacoes (id) on delete restrict,
  status text not null default 'publicado',
  avaliado_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint avaliacoes_tipo_check
    check (tipo_lancamento in ('parcial', 'revisao', 'fechamento')),
  constraint avaliacoes_status_check
    check (status in ('rascunho', 'publicado', 'cancelado')),
  constraint avaliacoes_revisao_tipo_check
    check (avaliacao_origem_id is null or tipo_lancamento = 'revisao'),
  constraint avaliacoes_revisao_raiz_check
    check (
      (avaliacao_origem_id is null and avaliacao_raiz_id is null)
      or (avaliacao_origem_id is not null and avaliacao_raiz_id is not null)
    )
);

create index if not exists idx_avaliacoes_matricula_turma_id
  on public.avaliacoes (matricula_turma_id, avaliado_em desc);
create index if not exists idx_avaliacoes_professor_id
  on public.avaliacoes (professor_id, avaliado_em desc);
create index if not exists idx_avaliacoes_semestre_id
  on public.avaliacoes (semestre_id);
create index if not exists idx_avaliacoes_origem_id
  on public.avaliacoes (avaliacao_origem_id);
create index if not exists idx_avaliacoes_raiz_id
  on public.avaliacoes (avaliacao_raiz_id, avaliado_em desc, created_at desc);

alter table public.avaliacoes
  add column if not exists avaliacao_origem_id uuid references public.avaliacoes (id) on delete restrict;

alter table public.avaliacoes
  add column if not exists avaliacao_raiz_id uuid references public.avaliacoes (id) on delete restrict;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'avaliacoes_revisao_tipo_check'
  ) then
    alter table public.avaliacoes
      add constraint avaliacoes_revisao_tipo_check
      check (avaliacao_origem_id is null or tipo_lancamento = 'revisao');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'avaliacoes_revisao_raiz_check'
  ) then
    alter table public.avaliacoes
      add constraint avaliacoes_revisao_raiz_check
      check (
        (avaliacao_origem_id is null and avaliacao_raiz_id is null)
        or (avaliacao_origem_id is not null and avaliacao_raiz_id is not null)
      );
  end if;
end;
$$;

create table if not exists public.itens_avaliados (
  id uuid primary key default gen_random_uuid(),
  avaliacao_id uuid not null references public.avaliacoes (id) on delete cascade,
  criterio_id uuid not null references public.criterios_avaliacao (id) on delete restrict,
  nota_bruta numeric(5,2) not null,
  peso_aplicado_percentual numeric(5,2) not null,
  nota_ponderada_percentual numeric(6,2)
    generated always as (round((nota_bruta / 10.0) * peso_aplicado_percentual, 2)) stored,
  feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint itens_avaliados_nota_bruta_check
    check (nota_bruta >= 0 and nota_bruta <= 10),
  constraint itens_avaliados_peso_check
    check (peso_aplicado_percentual > 0 and peso_aplicado_percentual <= 100),
  constraint itens_avaliados_uk unique (avaliacao_id, criterio_id)
);

create index if not exists idx_itens_avaliados_criterio_id on public.itens_avaliados (criterio_id);
create index if not exists idx_itens_avaliados_avaliacao_id on public.itens_avaliados (avaliacao_id);

create table if not exists public.ausencias (
  id uuid primary key default gen_random_uuid(),
  matricula_turma_id uuid not null references public.matriculas_turma (id) on delete restrict,
  registrado_por uuid not null references public.usuarios (id) on delete restrict,
  data_ausencia date not null,
  horas numeric(5,2) not null,
  justificada boolean not null default false,
  motivo text,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ausencias_horas_check check (horas > 0)
);

create index if not exists idx_ausencias_matricula_turma_id on public.ausencias (matricula_turma_id);
create index if not exists idx_ausencias_data_ausencia on public.ausencias (data_ausencia);
create index if not exists idx_ausencias_justificada on public.ausencias (justificada);

create table if not exists public.pacientes_clinica (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  identificador varchar(40) not null,
  nome text not null,
  data_nascimento date,
  cpf varchar(20),
  contato text,
  acompanhante text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_pacientes_clinica_unidade_identificador_uk
  on public.pacientes_clinica (unidade_id, identificador);

create unique index if not exists idx_pacientes_clinica_unidade_cpf_uk
  on public.pacientes_clinica (unidade_id, cpf)
  where cpf is not null and trim(cpf) <> '';

create index if not exists idx_pacientes_clinica_unidade_id
  on public.pacientes_clinica (unidade_id, ativo);

create table if not exists public.casos_clinicos (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  paciente_id uuid not null references public.pacientes_clinica (id) on delete restrict,
  matricula_turma_id uuid not null references public.matriculas_turma (id) on delete restrict,
  professor_id uuid not null references public.professores (usuario_id) on delete restrict,
  semestre_id uuid not null references public.semestres (id) on delete restrict,
  turma_id uuid not null references public.turmas (id) on delete restrict,
  area_estagio_id uuid references public.areas_estagio (id) on delete restrict,
  dia_semana text not null,
  horario_atendimento time not null,
  status text not null default 'atribuido',
  ativo boolean not null default true,
  data_inicio date not null default current_date,
  data_fim date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint casos_clinicos_status_check
    check (status in ('atribuido', 'ativo', 'encerrado', 'alta')),
  constraint casos_clinicos_dia_semana_check
    check (dia_semana in ('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado')),
  constraint casos_clinicos_periodo_check
    check (data_fim is null or data_fim >= data_inicio)
);

create unique index if not exists idx_casos_clinicos_unico_ativo
  on public.casos_clinicos (paciente_id, matricula_turma_id, semestre_id)
  where ativo = true;

create index if not exists idx_casos_clinicos_unidade_id
  on public.casos_clinicos (unidade_id, status, ativo);

create index if not exists idx_casos_clinicos_professor_id
  on public.casos_clinicos (professor_id, status, ativo);

create index if not exists idx_casos_clinicos_matricula_turma_id
  on public.casos_clinicos (matricula_turma_id, status, ativo);

create table if not exists public.casos_clinicos_horarios (
  id uuid primary key default gen_random_uuid(),
  caso_clinico_id uuid not null references public.casos_clinicos (id) on delete cascade,
  dia_semana text not null,
  horario_atendimento time not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint casos_clinicos_horarios_dia_semana_check
    check (dia_semana in ('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado'))
);

create unique index if not exists idx_casos_clinicos_horarios_unico
  on public.casos_clinicos_horarios (caso_clinico_id, dia_semana, horario_atendimento);

create index if not exists idx_casos_clinicos_horarios_caso_id
  on public.casos_clinicos_horarios (caso_clinico_id, dia_semana, horario_atendimento);

insert into public.casos_clinicos_horarios (
  caso_clinico_id,
  dia_semana,
  horario_atendimento
)
select
  c.id,
  c.dia_semana,
  c.horario_atendimento
from public.casos_clinicos c
where not exists (
  select 1
  from public.casos_clinicos_horarios h
  where h.caso_clinico_id = c.id
);

create table if not exists public.registros_clinicos (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  caso_clinico_id uuid not null references public.casos_clinicos (id) on delete cascade,
  tipo text not null,
  status text not null default 'rascunho',
  conteudo_json jsonb not null default '{}'::jsonb,
  parecer_supervisor text,
  autor_id uuid not null references public.usuarios (id) on delete restrict,
  revisado_por uuid references public.usuarios (id) on delete restrict,
  enviado_em timestamptz,
  revisado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint registros_clinicos_tipo_check
    check (tipo in ('avaliacao', 'plano_tratamento', 'evolucao')),
  constraint registros_clinicos_status_check
    check (status in ('rascunho', 'enviado', 'aprovado', 'ajustes_solicitados'))
);

drop index if exists public.idx_registros_clinicos_caso_tipo_uk;

create unique index if not exists idx_registros_clinicos_avaliacao_uk
  on public.registros_clinicos (caso_clinico_id)
  where tipo = 'avaliacao';

create unique index if not exists idx_registros_clinicos_plano_tratamento_uk
  on public.registros_clinicos (caso_clinico_id)
  where tipo = 'plano_tratamento';

create unique index if not exists idx_registros_clinicos_evolucao_data_uk
  on public.registros_clinicos (
    caso_clinico_id,
    ((conteudo_json ->> 'sessionDate'))
  )
  where tipo = 'evolucao'
    and coalesce(conteudo_json ->> 'sessionDate', '') <> '';

create index if not exists idx_registros_clinicos_unidade_status
  on public.registros_clinicos (unidade_id, status);

create index if not exists idx_registros_clinicos_autor_id
  on public.registros_clinicos (autor_id, updated_at desc);

create table if not exists public.notificacoes_clinicas (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  usuario_id uuid not null references public.usuarios (id) on delete cascade,
  caso_clinico_id uuid not null references public.casos_clinicos (id) on delete cascade,
  registro_clinico_id uuid references public.registros_clinicos (id) on delete cascade,
  tipo text not null,
  titulo text not null,
  mensagem text not null,
  lida boolean not null default false,
  lida_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notificacoes_clinicas_tipo_check
    check (
      tipo in (
        'avaliacao_enviada_supervisao',
        'avaliacao_ajustes_solicitados',
        'avaliacao_aprovada',
        'plano_tratamento_enviado_supervisao',
        'plano_tratamento_ajustes_solicitados',
        'plano_tratamento_aprovado',
        'evolucao_enviada_supervisao',
        'evolucao_ajustes_solicitados',
        'evolucao_aprovada'
      )
    )
);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conname = 'notificacoes_clinicas_tipo_check'
      and conrelid = 'public.notificacoes_clinicas'::regclass
  ) then
    alter table public.notificacoes_clinicas
      drop constraint notificacoes_clinicas_tipo_check;
  end if;

  alter table public.notificacoes_clinicas
    add constraint notificacoes_clinicas_tipo_check
    check (
      tipo in (
        'avaliacao_enviada_supervisao',
        'avaliacao_ajustes_solicitados',
        'avaliacao_aprovada',
        'plano_tratamento_enviado_supervisao',
        'plano_tratamento_ajustes_solicitados',
        'plano_tratamento_aprovado',
        'evolucao_enviada_supervisao',
        'evolucao_ajustes_solicitados',
        'evolucao_aprovada'
      )
    );
end;
$$;

create index if not exists idx_notificacoes_clinicas_usuario_lida
  on public.notificacoes_clinicas (usuario_id, lida, created_at desc);

create index if not exists idx_notificacoes_clinicas_caso
  on public.notificacoes_clinicas (caso_clinico_id, created_at desc);

create table if not exists public.documentos_aluno (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  aluno_id uuid not null references public.alunos (usuario_id) on delete restrict,
  matricula_turma_id uuid references public.matriculas_turma (id) on delete restrict,
  area_estagio_id uuid references public.areas_estagio (id) on delete restrict,
  tipo text not null,
  status text not null default 'enviado',
  arquivo_nome text not null,
  arquivo_mime_type text not null,
  arquivo_tamanho_bytes integer not null,
  storage_path text not null,
  observacao_validacao text,
  ativo boolean not null default true,
  versao integer not null default 1,
  documento_anterior_id uuid references public.documentos_aluno (id) on delete restrict,
  validado_por uuid references public.usuarios (id) on delete restrict,
  validado_por_papel text,
  enviado_em timestamptz not null default now(),
  validado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint documentos_aluno_tipo_check
    check (tipo in ('carteira_vacinacao', 'tce')),
  constraint documentos_aluno_status_check
    check (status in ('enviado', 'aprovado', 'reprovado')),
  constraint documentos_aluno_validador_papel_check
    check (
      validado_por_papel is null
      or validado_por_papel in ('professor', 'coordenador')
    ),
  constraint documentos_aluno_tamanho_check
    check (arquivo_tamanho_bytes > 0),
  constraint documentos_aluno_versao_check
    check (versao > 0),
  constraint documentos_aluno_tipo_relacao_check
    check (
      (
        tipo = 'carteira_vacinacao'
        and matricula_turma_id is null
        and area_estagio_id is null
      )
      or (
        tipo = 'tce'
        and matricula_turma_id is not null
        and area_estagio_id is not null
      )
    ),
  constraint documentos_aluno_validacao_consistencia_check
    check (
      (
        status = 'enviado'
        and validado_em is null
        and validado_por is null
        and validado_por_papel is null
      )
      or (
        status in ('aprovado', 'reprovado')
        and validado_em is not null
        and validado_por is not null
        and validado_por_papel is not null
      )
    ),
  constraint documentos_aluno_reprovacao_obrigatoria_check
    check (
      status <> 'reprovado'
      or nullif(trim(coalesce(observacao_validacao, '')), '') is not null
    )
);

create unique index if not exists idx_documentos_aluno_storage_path_uk
  on public.documentos_aluno (storage_path);

create unique index if not exists idx_documentos_aluno_carteira_ativa_uk
  on public.documentos_aluno (aluno_id)
  where tipo = 'carteira_vacinacao'
    and ativo = true;

create unique index if not exists idx_documentos_aluno_tce_ativo_uk
  on public.documentos_aluno (aluno_id, matricula_turma_id)
  where tipo = 'tce'
    and ativo = true
    and matricula_turma_id is not null;

create index if not exists idx_documentos_aluno_aluno_tipo
  on public.documentos_aluno (aluno_id, tipo, ativo, created_at desc);

create index if not exists idx_documentos_aluno_matricula_tipo
  on public.documentos_aluno (matricula_turma_id, tipo, ativo, created_at desc);

create index if not exists idx_documentos_aluno_unidade_status
  on public.documentos_aluno (unidade_id, status, created_at desc);

create index if not exists idx_documentos_aluno_area
  on public.documentos_aluno (area_estagio_id, tipo, created_at desc);

create table if not exists public.notificacoes_documentos_aluno (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid references public.unidades (id) on delete restrict,
  usuario_id uuid not null references public.usuarios (id) on delete cascade,
  documento_id uuid not null references public.documentos_aluno (id) on delete cascade,
  tipo text not null,
  titulo text not null,
  mensagem text not null,
  lida boolean not null default false,
  lida_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notificacoes_documentos_aluno_tipo_check
    check (
      tipo in (
        'documento_reprovado_professor',
        'documento_reprovado_coordenador'
      )
    ),
  constraint notificacoes_documentos_aluno_lida_check
    check (lida = false or lida_em is not null)
);

create index if not exists idx_notificacoes_documentos_aluno_usuario_lida
  on public.notificacoes_documentos_aluno (usuario_id, lida, created_at desc);

create index if not exists idx_notificacoes_documentos_aluno_documento
  on public.notificacoes_documentos_aluno (documento_id, created_at desc);

create table if not exists public.acessos_sistema (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios (id) on delete cascade,
  unidade_id uuid references public.unidades (id) on delete restrict,
  nome_usuario text not null,
  email citext,
  perfil text,
  acessado_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint acessos_sistema_perfil_check
    check (
      perfil is null
      or perfil in (
        'aluno',
        'professor',
        'secretaria',
        'coordenador',
        'coordenador_master'
      )
    )
);

create index if not exists idx_acessos_sistema_unidade_data
  on public.acessos_sistema (unidade_id, acessado_em desc);

create index if not exists idx_acessos_sistema_usuario_data
  on public.acessos_sistema (usuario_id, acessado_em desc);

create table if not exists public.liberacoes_excepcionais (
  id uuid primary key default gen_random_uuid(),
  unidade_id uuid not null references public.unidades (id) on delete restrict,
  semestre_id uuid not null references public.semestres (id) on delete restrict,
  turma_id uuid references public.turmas (id) on delete restrict,
  aluno_id uuid references public.alunos (usuario_id) on delete restrict,
  usuario_autorizado_id uuid not null references public.usuarios (id) on delete restrict,
  tipo text not null,
  escopo text not null,
  motivo text not null,
  criado_por uuid not null references public.usuarios (id) on delete restrict,
  inicio_em timestamptz not null default now(),
  expira_em timestamptz not null,
  ativo boolean not null default true,
  encerrado_manualmente_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint liberacoes_excepcionais_tipo_check
    check (tipo in ('avaliacao', 'ausencia', 'clinica_supervisionada')),
  constraint liberacoes_excepcionais_escopo_check
    check (escopo in ('semestre', 'turma', 'aluno')),
  constraint liberacoes_excepcionais_motivo_check
    check (nullif(trim(motivo), '') is not null),
  constraint liberacoes_excepcionais_periodo_check
    check (expira_em > inicio_em),
  constraint liberacoes_excepcionais_encerramento_consistencia_check
    check (
      encerrado_manualmente_em is null
      or (
        encerrado_manualmente_em >= inicio_em
        and ativo = false
      )
    ),
  constraint liberacoes_excepcionais_escopo_consistencia_check
    check (
      (
        escopo = 'semestre'
        and turma_id is null
        and aluno_id is null
      )
      or (
        escopo = 'turma'
        and turma_id is not null
        and aluno_id is null
      )
      or (
        escopo = 'aluno'
        and aluno_id is not null
      )
    )
);

create index if not exists idx_liberacoes_excepcionais_lookup
  on public.liberacoes_excepcionais (
    usuario_autorizado_id,
    tipo,
    ativo,
    unidade_id,
    semestre_id,
    inicio_em,
    expira_em desc
  );

create index if not exists idx_liberacoes_excepcionais_unidade_created_at
  on public.liberacoes_excepcionais (unidade_id, created_at desc);

create index if not exists idx_liberacoes_excepcionais_turma
  on public.liberacoes_excepcionais (turma_id, tipo, ativo, expira_em desc)
  where turma_id is not null;

create index if not exists idx_liberacoes_excepcionais_aluno
  on public.liberacoes_excepcionais (aluno_id, tipo, ativo, expira_em desc)
  where aluno_id is not null;

create table if not exists public.historico_alteracoes (
  id bigserial primary key,
  tabela text not null,
  registro_id uuid,
  acao text not null,
  dados_antes jsonb,
  dados_depois jsonb,
  usuario_id uuid,
  unidade_id uuid references public.unidades (id) on delete restrict,
  liberacao_excepcional_id uuid references public.liberacoes_excepcionais (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint historico_alteracoes_acao_check
    check (acao in ('INSERT', 'UPDATE', 'DELETE'))
);

alter table public.historico_alteracoes
  add column if not exists unidade_id uuid references public.unidades (id) on delete restrict;

alter table public.historico_alteracoes
  add column if not exists liberacao_excepcional_id uuid references public.liberacoes_excepcionais (id) on delete set null;

create index if not exists idx_historico_alteracoes_tabela_registro
  on public.historico_alteracoes (tabela, registro_id);
create index if not exists idx_historico_alteracoes_usuario_id
  on public.historico_alteracoes (usuario_id, created_at desc);
create index if not exists idx_historico_alteracoes_unidade_id
  on public.historico_alteracoes (unidade_id, created_at desc);
create index if not exists idx_historico_alteracoes_liberacao_excepcional_id
  on public.historico_alteracoes (liberacao_excepcional_id, created_at desc);

create or replace function private.current_exceptional_release_id()
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  release_id_text text;
begin
  release_id_text := nullif(trim(current_setting('app.exceptional_release_id', true)), '');

  if release_id_text is null then
    return null;
  end if;

  begin
    return release_id_text::uuid;
  exception
    when invalid_text_representation then
      return null;
  end;
end;
$$;

create or replace function private.set_current_exceptional_release_id(
  p_liberacao_excepcional_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform set_config(
    'app.exceptional_release_id',
    coalesce(p_liberacao_excepcional_id::text, ''),
    true
  );
end;
$$;

create or replace function private.validate_exceptional_release_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  semester_unit_id uuid;
  turma_semester_id uuid;
  student_unit_id uuid;
  authorized_user_unit_id uuid;
  creator_user_unit_id uuid;
begin
  select s.unidade_id
  into semester_unit_id
  from public.semestres s
  where s.id = new.semestre_id
  limit 1;

  if semester_unit_id is null then
    raise exception 'Semestre inválido para a liberação excepcional.';
  end if;

  if new.unidade_id is distinct from semester_unit_id then
    raise exception 'A unidade da liberação excepcional deve coincidir com a unidade do semestre.';
  end if;

  if new.encerrado_manualmente_em is not null then
    new.ativo := false;
  end if;

  if new.turma_id is not null then
    select t.semestre_id
    into turma_semester_id
    from public.turmas t
    where t.id = new.turma_id
    limit 1;

    if turma_semester_id is null then
      raise exception 'Turma inválida para a liberação excepcional.';
    end if;

    if turma_semester_id is distinct from new.semestre_id then
      raise exception 'A turma da liberação excepcional deve pertencer ao semestre informado.';
    end if;
  end if;

  if new.aluno_id is not null then
    select coalesce(a.unidade_id, u.unidade_id)
    into student_unit_id
    from public.alunos a
    left join public.usuarios u on u.id = a.usuario_id
    where a.usuario_id = new.aluno_id
    limit 1;

    if student_unit_id is null then
      raise exception 'Aluno inválido para a liberação excepcional.';
    end if;

    if student_unit_id is distinct from new.unidade_id then
      raise exception 'O aluno informado deve pertencer à mesma unidade da liberação excepcional.';
    end if;

    if not exists (
      select 1
      from public.matriculas_turma m
      join public.turmas t on t.id = m.turma_id
      where m.aluno_id = new.aluno_id
        and t.semestre_id = new.semestre_id
        and (new.turma_id is null or m.turma_id = new.turma_id)
    ) then
      raise exception 'O aluno informado não possui vínculo acadêmico compatível com o escopo da liberação excepcional.';
    end if;
  end if;

  select u.unidade_id
  into authorized_user_unit_id
  from public.usuarios u
  where u.id = new.usuario_autorizado_id
  limit 1;

  if authorized_user_unit_id is null then
    raise exception 'Usuário autorizado inválido para a liberação excepcional.';
  end if;

  if authorized_user_unit_id is distinct from new.unidade_id then
    raise exception 'O usuário autorizado deve pertencer à mesma unidade da liberação excepcional.';
  end if;

  select u.unidade_id
  into creator_user_unit_id
  from public.usuarios u
  where u.id = new.criado_por
  limit 1;

  if creator_user_unit_id is distinct from new.unidade_id
    and not exists (
      select 1
      from public.coordenadores_master cm
      where cm.usuario_id = new.criado_por
    ) then
    raise exception 'O criador da liberação excepcional deve pertencer à unidade ou ser coordenador master.';
  end if;

  return new;
end;
$$;

create or replace function public.obter_liberacao_excepcional_ativa(
  p_tipo text,
  p_semestre_id uuid,
  p_turma_id uuid default null,
  p_aluno_id uuid default null,
  p_usuario_id uuid default null,
  p_unidade_id uuid default null,
  p_referencia_em timestamptz default now()
)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  with contexto as (
    select
      coalesce(p_usuario_id, auth.uid()) as usuario_id,
      coalesce(p_unidade_id, s.unidade_id) as unidade_id,
      p_semestre_id as semestre_id,
      p_turma_id as turma_id,
      p_aluno_id as aluno_id,
      coalesce(p_referencia_em, now()) as referencia_em
    from public.semestres s
    where s.id = p_semestre_id
  )
  select le.id
  from public.liberacoes_excepcionais le
  join contexto c
    on c.unidade_id = le.unidade_id
   and c.semestre_id = le.semestre_id
  where c.usuario_id is not null
    and (
      c.usuario_id = (select auth.uid())
      or private.can_admin_unit(c.unidade_id)
      or private.is_master_coordinator()
    )
    and le.usuario_autorizado_id = c.usuario_id
    and le.tipo = p_tipo
    and le.ativo = true
    and le.encerrado_manualmente_em is null
    and c.referencia_em >= le.inicio_em
    and c.referencia_em <= le.expira_em
    and (
      le.escopo = 'semestre'
      or (
        le.escopo = 'turma'
        and c.turma_id is not null
        and le.turma_id = c.turma_id
      )
      or (
        le.escopo = 'aluno'
        and c.aluno_id is not null
        and le.aluno_id = c.aluno_id
        and (
          le.turma_id is null
          or (
            c.turma_id is not null
            and le.turma_id = c.turma_id
          )
        )
      )
    )
  order by
    case le.escopo
      when 'aluno' then 3
      when 'turma' then 2
      else 1
    end desc,
    le.expira_em asc,
    le.created_at desc
  limit 1;
$$;

create or replace function public.tem_liberacao_excepcional_ativa(
  p_tipo text,
  p_semestre_id uuid,
  p_turma_id uuid default null,
  p_aluno_id uuid default null,
  p_usuario_id uuid default null,
  p_unidade_id uuid default null,
  p_referencia_em timestamptz default now()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.obter_liberacao_excepcional_ativa(
    p_tipo => p_tipo,
    p_semestre_id => p_semestre_id,
    p_turma_id => p_turma_id,
    p_aluno_id => p_aluno_id,
    p_usuario_id => p_usuario_id,
    p_unidade_id => p_unidade_id,
    p_referencia_em => p_referencia_em
  ) is not null;
$$;

create or replace function public.vincular_liberacao_excepcional_auditoria(
  p_liberacao_excepcional_id uuid,
  p_tabela text,
  p_registro_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Usuário autenticado não encontrado para vincular a auditoria.';
  end if;

  if p_liberacao_excepcional_id is null then
    return 0;
  end if;

  if p_registro_ids is null or array_length(p_registro_ids, 1) is null then
    return 0;
  end if;

  if not exists (
    select 1
    from public.liberacoes_excepcionais le
    where le.id = p_liberacao_excepcional_id
      and le.usuario_autorizado_id = auth.uid()
  ) then
    raise exception 'A liberação excepcional informada não pertence ao usuário autenticado.';
  end if;

  update public.historico_alteracoes h
  set liberacao_excepcional_id = p_liberacao_excepcional_id
  where h.tabela = p_tabela
    and h.registro_id = any(p_registro_ids)
    and (h.usuario_id = auth.uid() or h.usuario_id is null)
    and h.liberacao_excepcional_id is null
    and h.created_at >= now() - interval '15 minutes';

  get diagnostics updated_count = row_count;

  return updated_count;
end;
$$;

create or replace function private.resolve_audit_unit_id(
  p_table_name text,
  p_record_data jsonb,
  p_actor_unit_id uuid default null
)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  resolved_unit_id uuid;
begin
  if p_record_data is null then
    return p_actor_unit_id;
  end if;

  begin
    resolved_unit_id :=
      nullif(trim(coalesce(p_record_data ->> 'unidade_id', '')), '')::uuid;
  exception
    when invalid_text_representation then
      resolved_unit_id := null;
  end;

  if resolved_unit_id is not null then
    return resolved_unit_id;
  end if;

  case p_table_name
    when 'usuarios' then
      select u.unidade_id
      into resolved_unit_id
      from public.usuarios u
      where u.id = nullif(p_record_data ->> 'id', '')::uuid
      limit 1;

    when 'alunos' then
      select coalesce(a.unidade_id, u.unidade_id)
      into resolved_unit_id
      from public.alunos a
      left join public.usuarios u on u.id = a.usuario_id
      where a.usuario_id = nullif(p_record_data ->> 'usuario_id', '')::uuid
      limit 1;

    when 'professores' then
      select coalesce(p.unidade_id, u.unidade_id)
      into resolved_unit_id
      from public.professores p
      left join public.usuarios u on u.id = p.usuario_id
      where p.usuario_id = nullif(p_record_data ->> 'usuario_id', '')::uuid
      limit 1;

    when 'coordenadores' then
      select coalesce(c.unidade_id, u.unidade_id)
      into resolved_unit_id
      from public.coordenadores c
      left join public.usuarios u on u.id = c.usuario_id
      where c.usuario_id = nullif(p_record_data ->> 'usuario_id', '')::uuid
      limit 1;

    when 'semestres' then
      select s.unidade_id
      into resolved_unit_id
      from public.semestres s
      where s.id = coalesce(
        nullif(p_record_data ->> 'id', '')::uuid,
        nullif(p_record_data ->> 'semestre_id', '')::uuid
      )
      limit 1;

    when 'turmas' then
      select s.unidade_id
      into resolved_unit_id
      from public.turmas t
      join public.semestres s on s.id = t.semestre_id
      where t.id = coalesce(
        nullif(p_record_data ->> 'id', '')::uuid,
        nullif(p_record_data ->> 'turma_id', '')::uuid
      )
      limit 1;

    when 'matriculas_turma', 'ausencias', 'vinculos_professor_aluno' then
      select s.unidade_id
      into resolved_unit_id
      from public.matriculas_turma m
      join public.turmas t on t.id = m.turma_id
      join public.semestres s on s.id = t.semestre_id
      where m.id = coalesce(
        nullif(p_record_data ->> 'id', '')::uuid,
        nullif(p_record_data ->> 'matricula_turma_id', '')::uuid
      )
      limit 1;

    when 'professor_areas_estagio' then
      select coalesce(p.unidade_id, u.unidade_id)
      into resolved_unit_id
      from public.professores p
      left join public.usuarios u on u.id = p.usuario_id
      where p.usuario_id = nullif(p_record_data ->> 'professor_id', '')::uuid
      limit 1;

    when 'avaliacoes' then
      select s.unidade_id
      into resolved_unit_id
      from public.semestres s
      where s.id = nullif(p_record_data ->> 'semestre_id', '')::uuid
      limit 1;

      if resolved_unit_id is null then
        select s.unidade_id
        into resolved_unit_id
        from public.matriculas_turma m
        join public.turmas t on t.id = m.turma_id
        join public.semestres s on s.id = t.semestre_id
        where m.id = nullif(p_record_data ->> 'matricula_turma_id', '')::uuid
        limit 1;
      end if;

    when 'itens_avaliados' then
      select s.unidade_id
      into resolved_unit_id
      from public.avaliacoes a
      join public.semestres s on s.id = a.semestre_id
      where a.id = nullif(p_record_data ->> 'avaliacao_id', '')::uuid
      limit 1;

    when 'pacientes_clinica' then
      select p.unidade_id
      into resolved_unit_id
      from public.pacientes_clinica p
      where p.id = coalesce(
        nullif(p_record_data ->> 'id', '')::uuid,
        nullif(p_record_data ->> 'paciente_id', '')::uuid
      )
      limit 1;

    when 'casos_clinicos' then
      select c.unidade_id
      into resolved_unit_id
      from public.casos_clinicos c
      where c.id = coalesce(
        nullif(p_record_data ->> 'id', '')::uuid,
        nullif(p_record_data ->> 'caso_clinico_id', '')::uuid
      )
      limit 1;

      if resolved_unit_id is null then
        select s.unidade_id
        into resolved_unit_id
        from public.semestres s
        where s.id = nullif(p_record_data ->> 'semestre_id', '')::uuid
        limit 1;
      end if;

    when 'casos_clinicos_horarios', 'registros_clinicos', 'notificacoes_clinicas' then
      select c.unidade_id
      into resolved_unit_id
      from public.casos_clinicos c
      where c.id = nullif(p_record_data ->> 'caso_clinico_id', '')::uuid
      limit 1;

    when 'documentos_aluno' then
      select d.unidade_id
      into resolved_unit_id
      from public.documentos_aluno d
      where d.id = coalesce(
        nullif(p_record_data ->> 'id', '')::uuid,
        nullif(p_record_data ->> 'documento_id', '')::uuid
      )
      limit 1;

    when 'notificacoes_documentos_aluno' then
      select d.unidade_id
      into resolved_unit_id
      from public.documentos_aluno d
      where d.id = nullif(p_record_data ->> 'documento_id', '')::uuid
      limit 1;
  end case;

  return coalesce(resolved_unit_id, p_actor_unit_id);
end;
$$;

create or replace function public.audit_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid;
  current_user_unit_id uuid;
  record_unit_id uuid;
  current_exceptional_release_id uuid;
  record_payload jsonb;
begin
  current_user_id := auth.uid();
  current_user_unit_id := (
    select u.unidade_id
    from public.usuarios u
    where u.id = current_user_id
    limit 1
  );

  if tg_op = 'DELETE' then
    record_payload := to_jsonb(old);
  else
    record_payload := to_jsonb(new);
  end if;

  current_exceptional_release_id := private.current_exceptional_release_id();

  record_unit_id := private.resolve_audit_unit_id(
    tg_table_name,
    record_payload,
    current_user_unit_id
  );

  if tg_op = 'INSERT' then
    insert into public.historico_alteracoes (
      tabela,
      registro_id,
      acao,
      dados_depois,
      usuario_id,
      unidade_id,
      liberacao_excepcional_id
    )
    values (
      tg_table_name,
      new.id,
      tg_op,
      to_jsonb(new),
      current_user_id,
      record_unit_id,
      current_exceptional_release_id
    );
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.historico_alteracoes (
      tabela,
      registro_id,
      acao,
      dados_antes,
      dados_depois,
      usuario_id,
      unidade_id,
      liberacao_excepcional_id
    )
    values (
      tg_table_name,
      new.id,
      tg_op,
      to_jsonb(old),
      to_jsonb(new),
      current_user_id,
      record_unit_id,
      current_exceptional_release_id
    );
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.historico_alteracoes (
      tabela,
      registro_id,
      acao,
      dados_antes,
      usuario_id,
      unidade_id,
      liberacao_excepcional_id
    )
    values (
      tg_table_name,
      old.id,
      tg_op,
      to_jsonb(old),
      current_user_id,
      record_unit_id,
      current_exceptional_release_id
    );
    return old;
  end if;

  return null;
end;
$$;

update public.historico_alteracoes h
set unidade_id = coalesce(
  private.resolve_audit_unit_id(
    h.tabela,
    coalesce(h.dados_depois, h.dados_antes),
    null
  ),
  (
    select u.unidade_id
    from public.usuarios u
    where u.id = h.usuario_id
    limit 1
  )
)
where h.unidade_id is null;

create or replace function public.registrar_acesso_sistema()
returns uuid
language plpgsql
set search_path = public
as $$
declare
  current_user_id uuid;
  current_user_record public.usuarios%rowtype;
  current_profile_code text;
  access_id uuid;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    raise exception 'Usuário autenticado não encontrado para registrar acesso.';
  end if;

  select u.*
  into current_user_record
  from public.usuarios u
  where u.id = current_user_id
    and u.ativo = true
  limit 1;

  if not found then
    raise exception 'Usuário ativo não encontrado para registrar acesso.';
  end if;

  select p.codigo
  into current_profile_code
  from public.perfis p
  where p.id = current_user_record.perfil_id
  limit 1;

  insert into public.acessos_sistema (
    usuario_id,
    unidade_id,
    nome_usuario,
    email,
    perfil
  )
  values (
    current_user_record.id,
    current_user_record.unidade_id,
    current_user_record.nome_completo,
    current_user_record.email,
    current_profile_code
  )
  returning id into access_id;

  return access_id;
end;
$$;

create or replace function public.sync_notificacoes_clinicas_avaliacao()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_professor_id uuid;
  v_student_id uuid;
  v_student_name text;
  v_patient_name text;
  v_notification_type text;
  v_title text;
  v_message text;
begin
  if new.tipo not in ('avaliacao', 'plano_tratamento', 'evolucao') then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.status is not distinct from new.status then
    return new;
  end if;

  select
    c.professor_id,
    mt.aluno_id,
    u.nome_completo,
    p.nome
  into
    v_professor_id,
    v_student_id,
    v_student_name,
    v_patient_name
  from public.casos_clinicos c
  join public.matriculas_turma mt on mt.id = c.matricula_turma_id
  join public.usuarios u on u.id = mt.aluno_id
  join public.pacientes_clinica p on p.id = c.paciente_id
  where c.id = new.caso_clinico_id
  limit 1;

  if v_professor_id is null or v_student_id is null then
    return new;
  end if;

  if new.status = 'enviado' and private.current_profile_code() = 'aluno' then
    if new.tipo = 'avaliacao' then
      v_notification_type := 'avaliacao_enviada_supervisao';
      v_title := 'Avaliacao enviada para supervisao';
      v_message :=
        coalesce(v_student_name, 'O aluno')
        || ' enviou a avaliacao de '
        || coalesce(v_patient_name, 'um paciente')
        || '.';
    elsif new.tipo = 'plano_tratamento' then
      v_notification_type := 'plano_tratamento_enviado_supervisao';
      v_title := 'Plano de tratamento enviado para supervisao';
      v_message :=
        coalesce(v_student_name, 'O aluno')
        || ' enviou o plano de tratamento de '
        || coalesce(v_patient_name, 'um paciente')
        || '.';
    else
      v_notification_type := 'evolucao_enviada_supervisao';
      v_title := 'Evolucao enviada para supervisao';
      v_message :=
        coalesce(v_student_name, 'O aluno')
        || ' enviou a evolucao de '
        || coalesce(v_patient_name, 'um paciente')
        || '.';
    end if;

    insert into public.notificacoes_clinicas (
      unidade_id,
      usuario_id,
      caso_clinico_id,
      registro_clinico_id,
      tipo,
      titulo,
      mensagem
    )
    values (
      new.unidade_id,
      v_professor_id,
      new.caso_clinico_id,
      new.id,
      v_notification_type,
      v_title,
      v_message
    );

    return new;
  end if;

  if
    new.status = 'ajustes_solicitados'
    and private.current_profile_code() = 'professor'
  then
    if new.tipo = 'avaliacao' then
      v_notification_type := 'avaliacao_ajustes_solicitados';
      v_title := 'Ajustes solicitados na avaliacao';
      v_message :=
        'O supervisor registrou parecer e solicitou ajustes na avaliacao de '
        || coalesce(v_patient_name, 'seu paciente')
        || '.';
    elsif new.tipo = 'plano_tratamento' then
      v_notification_type := 'plano_tratamento_ajustes_solicitados';
      v_title := 'Ajustes solicitados no plano de tratamento';
      v_message :=
        'O supervisor registrou parecer e solicitou ajustes no plano de tratamento de '
        || coalesce(v_patient_name, 'seu paciente')
        || '.';
    else
      v_notification_type := 'evolucao_ajustes_solicitados';
      v_title := 'Ajustes solicitados na evolucao';
      v_message :=
        'O supervisor registrou parecer e solicitou ajustes na evolucao de '
        || coalesce(v_patient_name, 'seu paciente')
        || '.';
    end if;

    insert into public.notificacoes_clinicas (
      unidade_id,
      usuario_id,
      caso_clinico_id,
      registro_clinico_id,
      tipo,
      titulo,
      mensagem
    )
    values (
      new.unidade_id,
      v_student_id,
      new.caso_clinico_id,
      new.id,
      v_notification_type,
      v_title,
      v_message
    );

    return new;
  end if;

  if new.status = 'aprovado' and private.current_profile_code() = 'professor' then
    if new.tipo = 'avaliacao' then
      v_notification_type := 'avaliacao_aprovada';
      v_title := 'Avaliacao aprovada';
      v_message :=
        'O supervisor aprovou a avaliacao de '
        || coalesce(v_patient_name, 'seu paciente')
        || '.';
    elsif new.tipo = 'plano_tratamento' then
      v_notification_type := 'plano_tratamento_aprovado';
      v_title := 'Plano de tratamento aprovado';
      v_message :=
        'O supervisor aprovou o plano de tratamento de '
        || coalesce(v_patient_name, 'seu paciente')
        || '.';
    else
      v_notification_type := 'evolucao_aprovada';
      v_title := 'Evolucao aprovada';
      v_message :=
        'O supervisor aprovou a evolucao de '
        || coalesce(v_patient_name, 'seu paciente')
        || '.';
    end if;

    insert into public.notificacoes_clinicas (
      unidade_id,
      usuario_id,
      caso_clinico_id,
      registro_clinico_id,
      tipo,
      titulo,
      mensagem
    )
    values (
      new.unidade_id,
      v_student_id,
      new.caso_clinico_id,
      new.id,
      v_notification_type,
      v_title,
      v_message
    );
  end if;

  return new;
end;
$$;

create or replace function private.current_profile_code()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.codigo
  from public.usuarios u
  join public.perfis p on p.id = u.perfil_id
  where u.id = (select auth.uid())
    and u.ativo = true
  limit 1;
$$;

create or replace function private.current_unit_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select u.unidade_id
  from public.usuarios u
  where u.id = (select auth.uid())
    and u.ativo = true
  limit 1;
$$;

create or replace function private.is_master_coordinator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(private.current_profile_code() = 'coordenador_master', false);
$$;

create or replace function private.is_unit_coordinator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(private.current_profile_code() = 'coordenador', false);
$$;

create or replace function private.is_coordinator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(private.current_profile_code() in ('coordenador', 'coordenador_master'), false);
$$;

create or replace function private.current_user_is_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.usuarios u
    where u.id = (select auth.uid())
      and u.ativo = true
  );
$$;

create or replace function private.can_access_unit(p_unidade_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and (
      private.is_master_coordinator()
      or (
        p_unidade_id is not null
        and private.current_unit_id() = p_unidade_id
      )
    );
$$;

create or replace function private.can_admin_unit(p_unidade_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select private.is_coordinator() and private.can_access_unit(p_unidade_id);
$$;

create or replace function private.can_operate_unit(p_unidade_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select private.is_unit_coordinator() and private.can_access_unit(p_unidade_id);
$$;

create or replace function private.is_student_active_for_matricula(p_matricula_turma_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.matriculas_turma m
    join public.usuarios u on u.id = m.aluno_id
    where m.id = p_matricula_turma_id
      and m.status = 'ativa'
      and u.ativo = true
  );
$$;

create or replace function private.is_professor_linked_to_matricula(p_matricula_turma_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select private.current_user_is_active()
    and exists (
    select 1
    from public.vinculos_professor_aluno v
    where v.professor_id = (select auth.uid())
      and v.matricula_turma_id = p_matricula_turma_id
      and v.ativo = true
      and (v.data_fim is null or v.data_fim >= current_date)
  );
$$;

create or replace function private.can_view_matricula(p_matricula_turma_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and (
      exists (
        select 1
        from public.matriculas_turma m
        join public.turmas t on t.id = m.turma_id
        join public.semestres s on s.id = t.semestre_id
        where m.id = p_matricula_turma_id
          and private.can_admin_unit(s.unidade_id)
      )
    or exists (
      select 1
      from public.matriculas_turma m
      where m.id = p_matricula_turma_id
        and m.aluno_id = (select auth.uid())
    )
    or private.is_professor_linked_to_matricula(p_matricula_turma_id)
    );
$$;

create or replace function private.can_manage_grades(p_matricula_turma_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and private.is_student_active_for_matricula(p_matricula_turma_id)
    and (
      exists (
        select 1
        from public.matriculas_turma m
        join public.turmas t on t.id = m.turma_id
        join public.semestres s on s.id = t.semestre_id
        where m.id = p_matricula_turma_id
          and private.can_operate_unit(s.unidade_id)
      )
      or private.is_professor_linked_to_matricula(p_matricula_turma_id)
    );
$$;

create or replace function private.can_assign_clinical_case(
  p_unidade_id uuid,
  p_matricula_turma_id uuid,
  p_professor_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and (
      (
        private.is_unit_coordinator()
        and private.can_access_unit(p_unidade_id)
      )
      or (
        private.current_profile_code() = 'professor'
        and p_professor_id = (select auth.uid())
        and private.can_access_unit(p_unidade_id)
        and private.can_manage_grades(p_matricula_turma_id)
      )
    );
$$;

create or replace function private.can_view_clinical_case(p_caso_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and exists (
      select 1
      from public.casos_clinicos c
      join public.matriculas_turma m on m.id = c.matricula_turma_id
      where c.id = p_caso_id
        and (
          private.can_admin_unit(c.unidade_id)
          or (
            private.current_profile_code() = 'professor'
            and c.professor_id = (select auth.uid())
          )
          or (
            private.current_profile_code() = 'aluno'
            and m.aluno_id = (select auth.uid())
          )
        )
    );
$$;

create or replace function private.can_manage_clinical_case(p_caso_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.casos_clinicos c
    where c.id = p_caso_id
      and private.can_assign_clinical_case(
        c.unidade_id,
        c.matricula_turma_id,
        c.professor_id
      )
  );
$$;

create or replace function private.can_view_professor(p_professor_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and (
      exists (
        select 1
        from public.professores p
        join public.usuarios u on u.id = p.usuario_id
        where p.usuario_id = p_professor_id
          and private.can_admin_unit(u.unidade_id)
      )
    or p_professor_id = (select auth.uid())
    or exists (
      select 1
      from public.vinculos_professor_aluno v
      join public.matriculas_turma m on m.id = v.matricula_turma_id
      where v.professor_id = p_professor_id
        and m.aluno_id = (select auth.uid())
        and v.ativo = true
        and (v.data_fim is null or v.data_fim >= current_date)
    );
    );
$$;

create or replace function private.can_view_student_document(p_documento_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and exists (
      select 1
      from public.documentos_aluno d
      where d.id = p_documento_id
        and (
          d.aluno_id = (select auth.uid())
          or private.can_admin_unit(d.unidade_id)
          or (
            private.current_profile_code() = 'professor'
            and (
              (
                d.tipo = 'carteira_vacinacao'
                and exists (
                  select 1
                  from public.matriculas_turma m
                  join public.vinculos_professor_aluno v
                    on v.matricula_turma_id = m.id
                  where m.aluno_id = d.aluno_id
                    and v.professor_id = (select auth.uid())
                    and v.ativo = true
                    and (v.data_fim is null or v.data_fim >= current_date)
                )
              )
              or (
                d.tipo = 'tce'
                and d.matricula_turma_id is not null
                and private.is_professor_linked_to_matricula(d.matricula_turma_id)
              )
            )
          )
        )
    );
$$;

create or replace function private.can_manage_student_document(p_documento_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and exists (
      select 1
      from public.documentos_aluno d
      where d.id = p_documento_id
        and (
          private.can_admin_unit(d.unidade_id)
          or (
            private.current_profile_code() = 'professor'
            and (
              (
                d.tipo = 'carteira_vacinacao'
                and exists (
                  select 1
                  from public.matriculas_turma m
                  join public.vinculos_professor_aluno v
                    on v.matricula_turma_id = m.id
                  where m.aluno_id = d.aluno_id
                    and v.professor_id = (select auth.uid())
                    and v.ativo = true
                    and (v.data_fim is null or v.data_fim >= current_date)
                )
              )
              or (
                d.tipo = 'tce'
                and d.matricula_turma_id is not null
                and private.is_professor_linked_to_matricula(d.matricula_turma_id)
              )
            )
          )
        )
    );
$$;

create or replace function public.calcular_resumo_semestral(p_matricula_turma_id uuid)
returns table (
  subtotal_percentual numeric(6,2),
  penalidade_percentual numeric(6,2),
  total_percentual numeric(6,2),
  equivalente_nota_10 numeric(5,2)
)
language sql
stable
security definer
set search_path = public
as $$
  with latest_items as (
    select distinct on (ia.criterio_id)
      ia.criterio_id,
      ia.nota_ponderada_percentual
    from public.itens_avaliados ia
    join public.avaliacoes a on a.id = ia.avaliacao_id
    where a.matricula_turma_id = p_matricula_turma_id
      and a.status = 'publicado'
    order by ia.criterio_id, a.avaliado_em desc, a.created_at desc, ia.created_at desc
  ),
  absence_penalty as (
    select coalesce(sum(horas), 0)::numeric(6,2) as penalidade_percentual
    from public.ausencias
    where matricula_turma_id = p_matricula_turma_id
      and justificada = false
  ),
  subtotal as (
    select coalesce(sum(nota_ponderada_percentual), 0)::numeric(6,2) as subtotal_percentual
    from latest_items
  )
  select
    s.subtotal_percentual,
    a.penalidade_percentual,
    greatest(s.subtotal_percentual - a.penalidade_percentual, 0)::numeric(6,2) as total_percentual,
    round(greatest(s.subtotal_percentual - a.penalidade_percentual, 0) / 10.0, 2)::numeric(5,2) as equivalente_nota_10
  from subtotal s
  cross join absence_penalty a;
$$;

create or replace function public.criar_avaliacao_com_itens(
  p_matricula_turma_id uuid,
  p_tipo_lancamento text,
  p_referencia text,
  p_observacoes text,
  p_status text,
  p_itens jsonb,
  p_avaliado_em timestamptz default now()
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_avaliacao_id uuid;
  v_semestre_id uuid;
  v_item jsonb;
  v_criterio_id uuid;
  v_nota_bruta numeric(5,2);
  v_feedback text;
  v_peso_percentual numeric(5,2);
begin
  if private.current_profile_code() <> 'professor' then
    raise exception 'Apenas professores podem criar avaliações por esta função.';
  end if;

  if not private.can_manage_grades(p_matricula_turma_id) then
    raise exception 'Professor sem vínculo ativo com a matrícula informada.';
  end if;

  if p_tipo_lancamento not in ('parcial', 'revisao', 'fechamento') then
    raise exception 'Tipo de lançamento inválido.';
  end if;

  if p_status not in ('rascunho', 'publicado') then
    raise exception 'Status de lançamento inválido.';
  end if;

  if trim(coalesce(p_referencia, '')) = '' then
    raise exception 'A referência do lançamento é obrigatória.';
  end if;

  if p_itens is null
    or jsonb_typeof(p_itens) <> 'array'
    or jsonb_array_length(p_itens) = 0 then
    raise exception 'É necessário informar ao menos um critério avaliado.';
  end if;

  select t.semestre_id
  into v_semestre_id
  from public.matriculas_turma mt
  join public.turmas t on t.id = mt.turma_id
  where mt.id = p_matricula_turma_id
  limit 1;

  if v_semestre_id is null then
    raise exception 'Não foi possível identificar o semestre da matrícula.';
  end if;

  insert into public.avaliacoes (
    matricula_turma_id,
    professor_id,
    semestre_id,
    tipo_lancamento,
    referencia,
    observacoes,
    status,
    avaliado_em
  )
  values (
    p_matricula_turma_id,
    auth.uid(),
    v_semestre_id,
    p_tipo_lancamento,
    trim(p_referencia),
    nullif(trim(coalesce(p_observacoes, '')), ''),
    p_status,
    coalesce(p_avaliado_em, now())
  )
  returning id into v_avaliacao_id;

  for v_item in
    select value
    from jsonb_array_elements(p_itens)
  loop
    v_criterio_id := nullif(v_item ->> 'criterio_id', '')::uuid;
    v_nota_bruta := nullif(v_item ->> 'nota_bruta', '')::numeric;
    v_feedback := nullif(trim(coalesce(v_item ->> 'feedback', '')), '');

    if v_criterio_id is null or v_nota_bruta is null then
      raise exception 'Item avaliado inválido.';
    end if;

    select c.peso_percentual
    into v_peso_percentual
    from public.criterios_avaliacao c
    where c.id = v_criterio_id
      and c.ativo = true
    limit 1;

    if v_peso_percentual is null then
      raise exception 'Critério de avaliação não encontrado ou inativo.';
    end if;

    insert into public.itens_avaliados (
      avaliacao_id,
      criterio_id,
      nota_bruta,
      peso_aplicado_percentual,
      feedback
    )
    values (
      v_avaliacao_id,
      v_criterio_id,
      v_nota_bruta,
      v_peso_percentual,
      v_feedback
    );
  end loop;

  return v_avaliacao_id;
end;
$$;

revoke all on function public.criar_avaliacao_com_itens(
  uuid,
  text,
  text,
  text,
  text,
  jsonb,
  timestamptz
) from public;

grant execute on function public.criar_avaliacao_com_itens(
  uuid,
  text,
  text,
  text,
  text,
  jsonb,
  timestamptz
) to authenticated;

create or replace function public.criar_revisao_avaliacao_com_itens(
  p_avaliacao_origem_id uuid,
  p_referencia text,
  p_observacoes text,
  p_status text,
  p_itens jsonb,
  p_avaliado_em timestamptz default now()
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_origem public.avaliacoes%rowtype;
  v_avaliacao_id uuid;
  v_item jsonb;
  v_criterio_id uuid;
  v_nota_bruta numeric(5,2);
  v_feedback text;
  v_peso_percentual numeric(5,2);
  v_existing_draft_id uuid;
  v_latest_published_id uuid;
begin
  if private.current_profile_code() <> 'professor' then
    raise exception 'Apenas professores podem criar revisoes por esta funcao.';
  end if;

  select *
  into v_origem
  from public.avaliacoes
  where id = p_avaliacao_origem_id
  limit 1;

  if v_origem.id is null then
    raise exception 'Lancamento de origem nao encontrado.';
  end if;

  if v_origem.professor_id <> auth.uid() then
    raise exception 'O lancamento informado nao pertence ao professor autenticado.';
  end if;

  if v_origem.status <> 'publicado' then
    raise exception 'A revisao incremental so pode partir de um lancamento publicado.';
  end if;

  if not private.can_manage_grades(v_origem.matricula_turma_id) then
    raise exception 'Professor sem vinculo ativo com a matricula informada.';
  end if;

  if p_status not in ('rascunho', 'publicado') then
    raise exception 'Status de lancamento invalido.';
  end if;

  if trim(coalesce(p_referencia, '')) = '' then
    raise exception 'A referencia da revisao e obrigatoria.';
  end if;

  if p_itens is null
    or jsonb_typeof(p_itens) <> 'array'
    or jsonb_array_length(p_itens) = 0 then
    raise exception 'E necessario informar ao menos um criterio alterado para a revisao.';
  end if;

  select a.id
  into v_latest_published_id
  from public.avaliacoes a
  where (
      a.id = coalesce(v_origem.avaliacao_raiz_id, v_origem.id)
      or a.avaliacao_raiz_id = coalesce(v_origem.avaliacao_raiz_id, v_origem.id)
    )
    and a.status = 'publicado'
  order by a.avaliado_em desc, a.created_at desc, a.id desc
  limit 1;

  if v_latest_published_id is distinct from v_origem.id then
    raise exception 'A revisao incremental deve partir da versao publicada mais recente desta cadeia.';
  end if;

  select a.id
  into v_existing_draft_id
  from public.avaliacoes a
  where a.avaliacao_origem_id = p_avaliacao_origem_id
    and a.professor_id = auth.uid()
    and a.status = 'rascunho'
  order by a.created_at desc
  limit 1;

  if v_existing_draft_id is not null then
    raise exception 'Ja existe um rascunho de revisao para este lancamento.';
  end if;

  insert into public.avaliacoes (
    matricula_turma_id,
    professor_id,
    semestre_id,
    tipo_lancamento,
    referencia,
    observacoes,
    avaliacao_origem_id,
    avaliacao_raiz_id,
    status,
    avaliado_em
  )
  values (
    v_origem.matricula_turma_id,
    auth.uid(),
    v_origem.semestre_id,
    'revisao',
    trim(p_referencia),
    nullif(trim(coalesce(p_observacoes, '')), ''),
    v_origem.id,
    coalesce(v_origem.avaliacao_raiz_id, v_origem.id),
    p_status,
    coalesce(p_avaliado_em, now())
  )
  returning id into v_avaliacao_id;

  for v_item in
    select value
    from jsonb_array_elements(p_itens)
  loop
    v_criterio_id := nullif(v_item ->> 'criterio_id', '')::uuid;
    v_nota_bruta := nullif(v_item ->> 'nota_bruta', '')::numeric;
    v_feedback := nullif(trim(coalesce(v_item ->> 'feedback', '')), '');

    if v_criterio_id is null or v_nota_bruta is null then
      raise exception 'Item revisado invalido.';
    end if;

    select c.peso_percentual
    into v_peso_percentual
    from public.criterios_avaliacao c
    where c.id = v_criterio_id
      and c.ativo = true
    limit 1;

    if v_peso_percentual is null then
      raise exception 'Criterio de avaliacao nao encontrado ou inativo.';
    end if;

    insert into public.itens_avaliados (
      avaliacao_id,
      criterio_id,
      nota_bruta,
      peso_aplicado_percentual,
      feedback
    )
    values (
      v_avaliacao_id,
      v_criterio_id,
      v_nota_bruta,
      v_peso_percentual,
      v_feedback
    );
  end loop;

  return v_avaliacao_id;
end;
$$;

revoke all on function public.criar_revisao_avaliacao_com_itens(
  uuid,
  text,
  text,
  text,
  jsonb,
  timestamptz
) from public;

grant execute on function public.criar_revisao_avaliacao_com_itens(
  uuid,
  text,
  text,
  text,
  jsonb,
  timestamptz
) to authenticated;

create or replace function public.atualizar_avaliacao_com_itens(
  p_avaliacao_id uuid,
  p_tipo_lancamento text,
  p_referencia text,
  p_observacoes text,
  p_status text,
  p_itens jsonb,
  p_avaliado_em timestamptz default now()
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_avaliacao public.avaliacoes%rowtype;
  v_item jsonb;
  v_criterio_id uuid;
  v_nota_bruta numeric(5,2);
  v_feedback text;
  v_peso_percentual numeric(5,2);
begin
  if private.current_profile_code() <> 'professor' then
    raise exception 'Apenas professores podem atualizar avaliacoes por esta funcao.';
  end if;

  select *
  into v_avaliacao
  from public.avaliacoes
  where id = p_avaliacao_id
  limit 1;

  if v_avaliacao.id is null then
    raise exception 'Lancamento de avaliacao nao encontrado.';
  end if;

  if v_avaliacao.professor_id <> auth.uid() then
    raise exception 'O lancamento informado nao pertence ao professor autenticado.';
  end if;

  if not private.can_manage_grades(v_avaliacao.matricula_turma_id) then
    raise exception 'Professor sem vinculo ativo com a matricula informada.';
  end if;

  if v_avaliacao.status <> 'rascunho' then
    raise exception 'Apenas lancamentos em rascunho podem ser alterados.';
  end if;

  if p_tipo_lancamento not in ('parcial', 'revisao', 'fechamento') then
    raise exception 'Tipo de lancamento invalido.';
  end if;

  if v_avaliacao.avaliacao_origem_id is not null and p_tipo_lancamento <> 'revisao' then
    raise exception 'Rascunhos de revisao vinculada devem permanecer com o tipo revisao.';
  end if;

  if p_status not in ('rascunho', 'publicado') then
    raise exception 'Status de lancamento invalido.';
  end if;

  if trim(coalesce(p_referencia, '')) = '' then
    raise exception 'A referencia do lancamento e obrigatoria.';
  end if;

  if p_itens is null
    or jsonb_typeof(p_itens) <> 'array'
    or jsonb_array_length(p_itens) = 0 then
    raise exception 'E necessario informar ao menos um criterio avaliado.';
  end if;

  update public.avaliacoes
  set
    tipo_lancamento = p_tipo_lancamento,
    referencia = trim(p_referencia),
    observacoes = nullif(trim(coalesce(p_observacoes, '')), ''),
    status = p_status,
    avaliado_em = coalesce(p_avaliado_em, avaliado_em)
  where id = p_avaliacao_id;

  delete from public.itens_avaliados
  where avaliacao_id = p_avaliacao_id;

  for v_item in
    select value
    from jsonb_array_elements(p_itens)
  loop
    v_criterio_id := nullif(v_item ->> 'criterio_id', '')::uuid;
    v_nota_bruta := nullif(v_item ->> 'nota_bruta', '')::numeric;
    v_feedback := nullif(trim(coalesce(v_item ->> 'feedback', '')), '');

    if v_criterio_id is null or v_nota_bruta is null then
      raise exception 'Item avaliado invalido.';
    end if;

    select c.peso_percentual
    into v_peso_percentual
    from public.criterios_avaliacao c
    where c.id = v_criterio_id
      and c.ativo = true
    limit 1;

    if v_peso_percentual is null then
      raise exception 'Criterio de avaliacao nao encontrado ou inativo.';
    end if;

    insert into public.itens_avaliados (
      avaliacao_id,
      criterio_id,
      nota_bruta,
      peso_aplicado_percentual,
      feedback
    )
    values (
      p_avaliacao_id,
      v_criterio_id,
      v_nota_bruta,
      v_peso_percentual,
      v_feedback
    );
  end loop;

  return p_avaliacao_id;
end;
$$;

revoke all on function public.atualizar_avaliacao_com_itens(
  uuid,
  text,
  text,
  text,
  text,
  jsonb,
  timestamptz
) from public;

grant execute on function public.atualizar_avaliacao_com_itens(
  uuid,
  text,
  text,
  text,
  text,
  jsonb,
  timestamptz
) to authenticated;

create or replace function private.can_view_student(p_aluno_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    private.current_user_is_active()
    and (
      exists (
        select 1
        from public.alunos a
        join public.usuarios u on u.id = a.usuario_id
        where a.usuario_id = p_aluno_id
          and private.can_admin_unit(u.unidade_id)
      )
    or p_aluno_id = (select auth.uid())
    or exists (
      select 1
      from public.matriculas_turma m
      join public.vinculos_professor_aluno v
        on v.matricula_turma_id = m.id
      where m.aluno_id = p_aluno_id
        and v.professor_id = (select auth.uid())
        and v.ativo = true
        and (v.data_fim is null or v.data_fim >= current_date)
    );
    );
$$;

drop trigger if exists trg_unidades_touch_updated_at on public.unidades;
create trigger trg_unidades_touch_updated_at
before update on public.unidades
for each row execute function public.touch_updated_at();

drop trigger if exists trg_usuarios_touch_updated_at on public.usuarios;
create trigger trg_usuarios_touch_updated_at
before update on public.usuarios
for each row execute function public.touch_updated_at();

drop trigger if exists trg_liberacoes_excepcionais_validate on public.liberacoes_excepcionais;
create trigger trg_liberacoes_excepcionais_validate
before insert or update on public.liberacoes_excepcionais
for each row execute function private.validate_exceptional_release_scope();

drop trigger if exists trg_liberacoes_excepcionais_touch_updated_at on public.liberacoes_excepcionais;
create trigger trg_liberacoes_excepcionais_touch_updated_at
before update on public.liberacoes_excepcionais
for each row execute function public.touch_updated_at();

drop trigger if exists trg_alunos_touch_updated_at on public.alunos;
create trigger trg_alunos_touch_updated_at
before update on public.alunos
for each row execute function public.touch_updated_at();

drop trigger if exists trg_professores_touch_updated_at on public.professores;
create trigger trg_professores_touch_updated_at
before update on public.professores
for each row execute function public.touch_updated_at();

drop trigger if exists trg_coordenadores_touch_updated_at on public.coordenadores;
create trigger trg_coordenadores_touch_updated_at
before update on public.coordenadores
for each row execute function public.touch_updated_at();

drop trigger if exists trg_coordenadores_master_touch_updated_at on public.coordenadores_master;
create trigger trg_coordenadores_master_touch_updated_at
before update on public.coordenadores_master
for each row execute function public.touch_updated_at();

drop trigger if exists trg_semestres_touch_updated_at on public.semestres;
create trigger trg_semestres_touch_updated_at
before update on public.semestres
for each row execute function public.touch_updated_at();

drop trigger if exists trg_blocos_estagio_touch_updated_at on public.blocos_estagio;
create trigger trg_blocos_estagio_touch_updated_at
before update on public.blocos_estagio
for each row execute function public.touch_updated_at();

drop trigger if exists trg_areas_estagio_touch_updated_at on public.areas_estagio;
create trigger trg_areas_estagio_touch_updated_at
before update on public.areas_estagio
for each row execute function public.touch_updated_at();

drop trigger if exists trg_turmas_touch_updated_at on public.turmas;
create trigger trg_turmas_touch_updated_at
before update on public.turmas
for each row execute function public.touch_updated_at();

drop trigger if exists trg_matriculas_turma_touch_updated_at on public.matriculas_turma;
create trigger trg_matriculas_turma_touch_updated_at
before update on public.matriculas_turma
for each row execute function public.touch_updated_at();

drop trigger if exists trg_professor_areas_estagio_touch_updated_at on public.professor_areas_estagio;
create trigger trg_professor_areas_estagio_touch_updated_at
before update on public.professor_areas_estagio
for each row execute function public.touch_updated_at();

drop trigger if exists trg_vinculos_professor_aluno_touch_updated_at on public.vinculos_professor_aluno;
create trigger trg_vinculos_professor_aluno_touch_updated_at
before update on public.vinculos_professor_aluno
for each row execute function public.touch_updated_at();

drop trigger if exists trg_grupos_avaliacao_touch_updated_at on public.grupos_avaliacao;
create trigger trg_grupos_avaliacao_touch_updated_at
before update on public.grupos_avaliacao
for each row execute function public.touch_updated_at();

drop trigger if exists trg_criterios_avaliacao_touch_updated_at on public.criterios_avaliacao;
create trigger trg_criterios_avaliacao_touch_updated_at
before update on public.criterios_avaliacao
for each row execute function public.touch_updated_at();

drop trigger if exists trg_avaliacoes_touch_updated_at on public.avaliacoes;
create trigger trg_avaliacoes_touch_updated_at
before update on public.avaliacoes
for each row execute function public.touch_updated_at();

drop trigger if exists trg_itens_avaliados_touch_updated_at on public.itens_avaliados;
create trigger trg_itens_avaliados_touch_updated_at
before update on public.itens_avaliados
for each row execute function public.touch_updated_at();

drop trigger if exists trg_ausencias_touch_updated_at on public.ausencias;
create trigger trg_ausencias_touch_updated_at
before update on public.ausencias
for each row execute function public.touch_updated_at();

drop trigger if exists trg_pacientes_clinica_touch_updated_at on public.pacientes_clinica;
create trigger trg_pacientes_clinica_touch_updated_at
before update on public.pacientes_clinica
for each row execute function public.touch_updated_at();

drop trigger if exists trg_casos_clinicos_touch_updated_at on public.casos_clinicos;
create trigger trg_casos_clinicos_touch_updated_at
before update on public.casos_clinicos
for each row execute function public.touch_updated_at();

drop trigger if exists trg_casos_clinicos_horarios_touch_updated_at on public.casos_clinicos_horarios;
create trigger trg_casos_clinicos_horarios_touch_updated_at
before update on public.casos_clinicos_horarios
for each row execute function public.touch_updated_at();

drop trigger if exists trg_registros_clinicos_touch_updated_at on public.registros_clinicos;
create trigger trg_registros_clinicos_touch_updated_at
before update on public.registros_clinicos
for each row execute function public.touch_updated_at();

drop trigger if exists trg_registros_clinicos_notificacoes on public.registros_clinicos;
create trigger trg_registros_clinicos_notificacoes
after insert or update on public.registros_clinicos
for each row execute function public.sync_notificacoes_clinicas_avaliacao();

drop trigger if exists trg_notificacoes_clinicas_touch_updated_at on public.notificacoes_clinicas;
create trigger trg_notificacoes_clinicas_touch_updated_at
before update on public.notificacoes_clinicas
for each row execute function public.touch_updated_at();

drop trigger if exists trg_documentos_aluno_touch_updated_at on public.documentos_aluno;
create trigger trg_documentos_aluno_touch_updated_at
before update on public.documentos_aluno
for each row execute function public.touch_updated_at();

drop trigger if exists trg_notificacoes_documentos_aluno_touch_updated_at on public.notificacoes_documentos_aluno;
create trigger trg_notificacoes_documentos_aluno_touch_updated_at
before update on public.notificacoes_documentos_aluno
for each row execute function public.touch_updated_at();

drop trigger if exists trg_avaliacoes_audit on public.avaliacoes;
create trigger trg_avaliacoes_audit
after insert or update or delete on public.avaliacoes
for each row execute function public.audit_changes();

drop trigger if exists trg_itens_avaliados_audit on public.itens_avaliados;
create trigger trg_itens_avaliados_audit
after insert or update or delete on public.itens_avaliados
for each row execute function public.audit_changes();

drop trigger if exists trg_ausencias_audit on public.ausencias;
create trigger trg_ausencias_audit
after insert or update or delete on public.ausencias
for each row execute function public.audit_changes();

drop trigger if exists trg_vinculos_professor_aluno_audit on public.vinculos_professor_aluno;
create trigger trg_vinculos_professor_aluno_audit
after insert or update or delete on public.vinculos_professor_aluno
for each row execute function public.audit_changes();

drop trigger if exists trg_usuarios_audit on public.usuarios;
create trigger trg_usuarios_audit
after insert or update or delete on public.usuarios
for each row execute function public.audit_changes();

drop trigger if exists trg_liberacoes_excepcionais_audit on public.liberacoes_excepcionais;
create trigger trg_liberacoes_excepcionais_audit
after insert or update or delete on public.liberacoes_excepcionais
for each row execute function public.audit_changes();

drop trigger if exists trg_alunos_audit on public.alunos;
create trigger trg_alunos_audit
after insert or update or delete on public.alunos
for each row execute function public.audit_changes();

drop trigger if exists trg_professores_audit on public.professores;
create trigger trg_professores_audit
after insert or update or delete on public.professores
for each row execute function public.audit_changes();

drop trigger if exists trg_blocos_estagio_audit on public.blocos_estagio;
create trigger trg_blocos_estagio_audit
after insert or update or delete on public.blocos_estagio
for each row execute function public.audit_changes();

drop trigger if exists trg_areas_estagio_audit on public.areas_estagio;
create trigger trg_areas_estagio_audit
after insert or update or delete on public.areas_estagio
for each row execute function public.audit_changes();

drop trigger if exists trg_turmas_audit on public.turmas;
create trigger trg_turmas_audit
after insert or update or delete on public.turmas
for each row execute function public.audit_changes();

drop trigger if exists trg_matriculas_turma_audit on public.matriculas_turma;
create trigger trg_matriculas_turma_audit
after insert or update or delete on public.matriculas_turma
for each row execute function public.audit_changes();

drop trigger if exists trg_professor_areas_estagio_audit on public.professor_areas_estagio;
create trigger trg_professor_areas_estagio_audit
after insert or update or delete on public.professor_areas_estagio
for each row execute function public.audit_changes();

drop trigger if exists trg_pacientes_clinica_audit on public.pacientes_clinica;
create trigger trg_pacientes_clinica_audit
after insert or update or delete on public.pacientes_clinica
for each row execute function public.audit_changes();

drop trigger if exists trg_casos_clinicos_audit on public.casos_clinicos;
create trigger trg_casos_clinicos_audit
after insert or update or delete on public.casos_clinicos
for each row execute function public.audit_changes();

drop trigger if exists trg_casos_clinicos_horarios_audit on public.casos_clinicos_horarios;
create trigger trg_casos_clinicos_horarios_audit
after insert or update or delete on public.casos_clinicos_horarios
for each row execute function public.audit_changes();

drop trigger if exists trg_registros_clinicos_audit on public.registros_clinicos;
create trigger trg_registros_clinicos_audit
after insert or update or delete on public.registros_clinicos
for each row execute function public.audit_changes();

drop trigger if exists trg_notificacoes_clinicas_audit on public.notificacoes_clinicas;
create trigger trg_notificacoes_clinicas_audit
after insert or update or delete on public.notificacoes_clinicas
for each row execute function public.audit_changes();

drop trigger if exists trg_documentos_aluno_audit on public.documentos_aluno;
create trigger trg_documentos_aluno_audit
after insert or update or delete on public.documentos_aluno
for each row execute function public.audit_changes();

drop trigger if exists trg_notificacoes_documentos_aluno_audit on public.notificacoes_documentos_aluno;
create trigger trg_notificacoes_documentos_aluno_audit
after insert or update or delete on public.notificacoes_documentos_aluno
for each row execute function public.audit_changes();
